cloud:
  aws:
    region:
      static: eu-west-1
      auto: false
    stack:
      auto: false
    credentials:
      accesskey: *************
      secretkey: ***************
    sqs:
      endpoint: https://sqs.eu-west-1.amazonaws.com/716651577445/products-queue
    dynamodb:
      endpoint: https://dynamodb.eu-west-1.amazonaws.com
server:
  port: 8080